# shopify.app.toml
client_id = "437477591e78677478825f6ba18475ce"
name = "whatsapp-float"
application_url = "https://cclab-f120.onrender.com/app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

# ❌ 不要 access_scopes（或保持空字符串）
# [access_scopes]
# scopes = ""

[auth]
redirect_urls = ["https://cclab-f120.onrender.com/auth/callback"]
