# Production config for Render deployment
client_id = "437477591e78677478825f6ba18475ce"
name = "whatsapp-float"
application_url = "https://cclab-f12o.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[auth]
redirect_urls = ["https://cclab-f12o.onrender.com/auth/callback"]

[access_scopes]
scopes = "read_products"
